services:
  web:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
